### ISSUE TITLE
Invalid argument(s): Unknown entity type PlayerEntity

### ISSUE THREAD

**Issue by QiXi** [objectbox/objectbox-dart#315]
First time trying to use objectbox on examples of documentation

Unhandled exception: Invalid argument(s): Unknown entity type PlayerEntity

Dart CLI apps
- ObjectBox version: ^1.2.0
- Dart SDK: 2.14.2 (stable) on "linux_x64"
- Null-safety enabled: yes
- Reproducibility: always
- OS: Ubuntu

### Steps to reproduce
1. Add ObjectBox to your project
2. Define Entity Classes
```dart
@Entity()
class PlayerEntity {
  int id = 0;
  String? text;
  @Property(type: PropertyType.date)
  DateTime date;
  PlayerEntity({this.text, DateTime? date}) : date = date ?? DateTime.now();
}
```
3. Generate ObjectBox code 
4. Run 
```dart
void main() async {
  final store = openStore();
  final box = store.box<PlayerEntity>();
  final note = PlayerEntity(text: 'Hello'); 
  final id = box.put(note);        
```
5. See error
> Unhandled exception:
> Invalid argument(s): Unknown entity type PlayerEntity
> #0      Store._entityDef (package:objectbox/src/native/store.dart:261:7)
> #1      Store.box (package:objectbox/src/native/store.dart:253:60)

**Comment by QiXi** [comment]
This is a problem due to erroneous import 
`import '../lib/objectbox.g.dart';`

> Avoid relative imports for files in `lib/`.
