### ISSUE TITLE
CocoaPods could not find compatible versions for pod "ObjectBox"

### ISSUE THREAD

**Issue by Ali-Atrash** [objectbox/objectbox-dart#329]
I couldn't solve this CocaPods problem although I tried everything I found in Stackoverflow. 

The error:
```
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "ObjectBox":
  In Podfile:
    objectbox_flutter_libs (from `.symlinks/plugins/objectbox_flutter_libs/ios`) was resolved to 0.0.1, which depends on
      ObjectBox (= 1.6.0)

    objectbox_sync_flutter_libs (from `.symlinks/plugins/objectbox_sync_flutter_libs/ios`) was resolved to 0.0.1, which depends on
      ObjectBox (= 1.6.0-sync)
```
My pubspec relevant data:
```
dependencies:
  objectbox: ^1.2.0
  objectbox_flutter_libs: any

dev_dependencies:
  objectbox_generator: ^1.2.0
  build_runner: ^2.1.4
```
In iOS Podfile:
```
platform :ios, '12.0'
```

Output of `flutter --version`
```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (2 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```
Null-safety enabled: yes

Reproducibility: occurred always

flutter doctor -v: all green with no issue found.

And this is the output of `flutter run`:

```
Launching lib/main.dart on iPhone 12 in debug mode...
Running pod install...                                           1,496ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (`$(ARCHS_STANDARD)`)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `flutter_secure_storage` from `.symlinks/plugins/flutter_secure_storage/ios`
    -> Fetching podspec for `objectbox_flutter_libs` from `.symlinks/plugins/objectbox_flutter_libs/ios`
    -> Fetching podspec for `objectbox_sync_flutter_libs` from `.symlinks/plugins/objectbox_sync_flutter_libs/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_7_d_b.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/7/d/b/ObjectBox/1.6.0/ObjectBox.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_f_4_e.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/7/d/b/ObjectBox/1.6.0-sync/ObjectBox.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/7/d/b/ObjectBox/1.6.0/ObjectBox.podspec.json exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "ObjectBox":
      In Podfile:
        objectbox_flutter_libs (from `.symlinks/plugins/objectbox_flutter_libs/ios`) was resolved to 0.0.1, which depends on
          ObjectBox (= 1.6.0)

        objectbox_sync_flutter_libs (from `.symlinks/plugins/objectbox_sync_flutter_libs/ios`) was resolved to 0.0.1, which depends on
          ObjectBox (= 1.6.0-sync)

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:700:in `attempt_to_filter_existing_spec'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:672:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone 12.
```

Can you help?

**Comment by greenrobot-team** [comment]
Do you mind sharing how you resolved this so other users having this same issue can fix it?

From the logs I guess the issue was the architectures in XCode not being configured to 64-bit only (see https://github.com/objectbox/objectbox-dart/blob/main/objectbox/README.md#flutter step for XCode/iOS).

**Comment by Ali-Atrash** [comment]
I did use `ARCHS_STANDARD_64_BIT` but it didn't work for me. I kept changing versions until this worked:
```
dependencies:
  objectbox: ^1.2.1-dev.0
  objectbox_flutter_libs: any

dev_dependencies:
  objectbox_generator: ^1.2.0
```
