### ISSUE TITLE
Unsupported operation: Could not load ObjectBox core dynamic library. Platform: ios

### ISSUE THREAD

**Issue by danieloquelis** [objectbox/objectbox-dart#339]
Exception when trying to initialize ObjectBox on ios:

`Unhandled Exception: Unsupported operation: Could not load ObjectBox core dynamic library. Platform: ios
`

- ObjectBox version: 1.2.1
- Flutter/Dart SDK: flutter 2.5.3
- Null-safety enabled: yes
- Reproducibility: always trying to start the app on ios
- OS: macOS BigSur
- Device/Emulator: iPhone 8 - iOS 15.0

### Steps to reproduce

1. Create a helper to get access to objectBox

```
class ObjectBox {
  late final Store store;

  ObjectBox._create(this.store) {
    // Add any additional setup code, e.g. build queries.
  }

  static Future<ObjectBox> create() async {
    // Future<Store> openStore() {...} is defined in the generated objectbox.g.dart
    final store = openStore();
    return ObjectBox._create(store);
  }
}
```

2. Create an instance on main class

```
late ObjectBox objectbox;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  objectbox = await ObjectBox.create();
  runApp(const MyApp());
}
```
3. run in debug mode, observe the console showing the exception

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Unsupported operation: Could not load ObjectBox core dynamic library. Platform: ios
#0      loadObjectBoxLib (package:objectbox/src/native/bindings/bindings.dart:69:5)
#1      C (package:objectbox/src/native/bindings/bindings.dart:84:27)
#2      C (package:objectbox/src/native/bindings/bindings.dart)
#3      new Model (package:objectbox/src/native/model.dart:19:31)
#4      new Store (package:objectbox/src/native/store.dart:105:21)
#5      openStore (package:dimexa_vendors/objectbox.g.dart:66:5)
#6      ObjectBox.create (package:dimexa_vendors/services/objectbox/objectbox.dart:12:19)
#7      main (package:dimexa_vendors/main.dart:14:31)
#8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:145:25)
#9      _rootRun (dart:async/zone.dart:1428:13)
#10     _CustomZone.run (dart:async/zone.dart:1328:19)
#11     _runZoned (dart:async/zone.dart:1863:10)
#12     runZonedGuarded (dart:async/zone.dart:1851:12)
#13     _runMainZon<…>
```

### Expected behavior

App running properly.

**Comment by danieloquelis** [comment]
Solved!

in the _pupspec.yml_ file I added also _"objectbox_flutter_libs: any"_

objectbox: ^1.2.1
objectbox_flutter_libs: any -> _this was missing_

**Comment by greenrobot-team** [comment]
Good to hear! You probably followed the default pub.dev installation instructions? But setup for ObjectBox is a little more involved, see https://pub.dev/packages/objectbox#getting-started
