### ISSUE TITLE
Unhandled Exception: ObjectBoxException: failed to create store: 10501 DB's last entity ID 2 is higher than 1 from model

### ISSUE THREAD

**Issue by alasriaj** [objectbox/objectbox-dart#483]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ObjectBoxException: failed to create store: 10501 DB's last entity ID 2 is higher than 1 from model
#0      ObjectBoxNativeError.throwMapped (package:objectbox/src/native/bindings/helpers.dart:78:9)
#1      throwLatestNativeError (package:objectbox/src/native/bindings/helpers.dart:50:48)
#2      checkObxPtr (package:objectbox/src/native/bindings/helpers.dart:32:5)
#3      Store._checkStorePointer (package:objectbox/src/native/store.dart:367:7)
#4      new Store (package:objectbox/src/native/store.dart:208:7)
#5      openStore (package:objectbox_flutter/objectbox.g.dart:56:5)
<asynchronous suspension>
#6      ObjectBox.init (package:objectbox_flutter/helper/object_box.dart:15:19)
<asynchronous suspension>
#7      main (package:objectbox_flutter/main.dart:10:15)
<asynchronous suspension>

**Comment by greenrobot-team** [comment]
See https://docs.objectbox.io/advanced/meta-model-ids-and-uids#resolving-meta-model-conflicts on why this happens and how to resolve it.
